apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  type: ClusterIP
  selector:
    app: discovery-service
  ports:
  - name: grpc
    port: 3000
    targetPort: grpc
    protocol: TCP
  - name: http
    port: 3001
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 2122
    targetPort: metrics
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service-grpc
  labels:
    app: discovery-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: discovery-service
  ports:
  - name: grpc
    port: 3000
    targetPort: grpc
    protocol: TCP
